# Generated by Django 4.0.1 on 2022-01-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('title', models.CharField(max_length=50, verbose_name='Название картинки')),
                ('photo', models.ImageField(blank=True, upload_to='static/img', verbose_name='картинка')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_images', to='places.excursion', verbose_name='экскурсия')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
