# Generated by Django 4.0.1 on 2022-01-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_image_excursion_remove_image_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='картинка'),
        ),
    ]
