# Generated by Django 4.0.1 on 2022-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_title_image_excursion'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер'),
        ),
    ]
