# Generated by Django 4.0.1 on 2022-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_excursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='description_short',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
    ]
