# Generated by Django 4.0.1 on 2022-02-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='lat',
            field=models.FloatField(verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='lon',
            field=models.FloatField(verbose_name='широта'),
        ),
    ]
