# Generated by Django 4.0.1 on 2022-02-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_excursion_lat_alter_excursion_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.excursion', verbose_name='название'),
        ),
    ]
